swagger: "2.0"
info:
  description: "Our API"
  version: "1.0.0"
  title: "my Title"
host: "localhost:5050"
basePath: "/"
schemes:
- "http"
paths:

  /users:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Created user Object"
          schema:
            $ref: "#/definitions/User"          
    get:
      tags:
      - "user"
      summary: "get users"
      description: "get Users."
      operationId: "GetUser"
      produces:
      - "application/json"
      responses:
        200:
          description: "slist of users"
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
              

definitions:

  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"

    xml:
      name: "User"

